### PR TITLE
Add threading support

### PR DESCRIPTION
**Pull request by vahtis**
Passing threading model -D_MT to clang when runtime library is set in visual studio project file.

### CODE REVIEW

**Comment by cpp-red-lion** [comment]
Hi,

There are multiple configurations for `RuntimeLibrary` setting in VS:

- /MTd  `<RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>`
- /MT    `<RuntimeLibrary>MultiThreaded</RuntimeLibrary>`

- /MD   `<RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>`
- /MDd  `<RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>`

**Comment by hero101111** [comment]
Will push a fix that will handle these four values.

**Comment by vahtis** [comment]
I tried different variations and I was not able to get anything else but -D_MT to work.
This is reason why I just use the -D_MT when found one of those values set.
Maybe I need to check boost source too.
I think that /MT and those are for visual studio compiler and after all we are compiling with clang.

**Comment by vahtis** [comment]
Here is verbose output from my most recent test
```
VERBOSE: INVOKE: "\clang++.exe" -x c++ "D:\source\vpv\laskenta\CalcControl\OCIConnection.cpp" -std=c++14 -Wall 
-fms-compatibility-version=19.10 -fms-compatibility -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas 
-Wno-unused-variable -Wno-unused-value -fsyntax-only "-DWIN32" "-D_DEBUG" "-D_CONSOLE"  /MT 
-D_DEBUG_FUNCTIONAL_MACHINERY -isystem"D:\source\vpv\laskenta\CalcControl" -isystem"C:\Program Files (x86)\Microsoft 
Visual Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\include" -isystem"C:\Program Files (x86)\Microsoft Visual 
Studio\2017\Professional\VC\Tools\MSVC\14.12.25827\atlmfc\include" -isystem"C:\Program Files (x86)\Windows 
Kits\10\Include\10.0.16299.0\ucrt" -isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\um" 
-isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.16299.0\shared" -isystem"C:\Program Files (x86)\Windows 
Kits\10\Include\10.0.16299.0\winrt" -isystem"D:\source\boost" -isystem"C:\instantclient_12_2_32bit\sdk\include"
1: D:\source\vpv\laskenta\CalcControl\OCIConnection.cpp
clang++.exe: error: no such file or directory: '/MT'
```

**Comment by cpp-red-lion** [comment]
Sorry about the lack of clarity on my part.

The values I listed above `/MTd /MT /MD /MDd` are switches for `cl.exe` corresponding to the different threading models/CRT linkage.

I'm not exactly sure about the corresponding _preprocessor defines_ needed. 
Visual Studio doesn't seem to pass anything related to this to `cl.exe` as `-D_some_define`

**Comment by vahtis** [comment]
Did some more searching and it seems to be that _MT is correct in all previously mentioned situations.

> _MT Defined as 1 when /MD or /MDd (Multithreaded DLL) or /MT or /MTd (Multithreaded) is specified. Otherwise, undefined.

[Source](https://msdn.microsoft.com/en-us/library/b0084kay.aspx)

**Comment by cpp-red-lion** [comment]
Excellent !

It's clear, now.
Thanks for the research, @vahtis 👍

**Pull request merged**
