### PR TITLE
Bugfix for install location of VS and extension for additional include determination

### PR DESCRIPTION
**Pull request by GerrietReents**
This PR contains two commits. One fixes an issue with VS not installed on C: drive. The other one improves the mechanism of include directory determination. The VCProjectEngine is used within the vs extension to collect all additional include directories including inherited property sheets. It also expands alle macros contained in the include paths.

### CODE REVIEW

**Comment by GerrietReents** [comment]
After some testing I realized, that my way of referencing the VCProjectEngine binds the extension to the VS version it is developed in. So, if the extension is developed in VS 2017 it will not work in VS 2015! 
I'm currently changing my usage to late binding and will update this PR accordingly!

**Comment by cpp-red-lion** [comment]
VS not installed on C: drive #30 was already fixed.

**Comment by cpp-red-lion** [comment]
For the rest of your PR, are you trying to fix something similar to #33  ?
You didn't reference any open issue, nor did create a new one.
I'm confused about the problem you're trying to solve...

**Comment by cpp-red-lion** [comment]
You're right, any solution involving `VCProjectEngine` will need to work both in VS2015 and VS2017.

**Comment by GerrietReents** [comment]
Hmm, #30 seems not to be on the master. At least Get-MscVer is still buggy there.

**Comment by GerrietReents** [comment]
I will create an issue for my problem to clarify the purpose of this PR. But #33 would be fixed, I think.

**Comment by cpp-red-lion** [comment]
Then, I would recommend (as a general good practice) to create a separate PR for each issue to be addressed. 
Eg. a separate PR for #30 issue (if it's currently incomplete)

**Comment by cpp-red-lion** [comment]
BTW, we already support project property sheet references (even nested ones), via our underlying PowerShell script.
Is there a specific issue/bug related to VS property sheets you found ?
Maybe the problems are related to MSBuild properties/macros...

**Comment by hero101111** [comment]
The MSCVER detection issue was [fixed](https://github.com/Caphyon/clang-power-tools/commit/79453abaf5c10936ed8e9ce9e22d18736fef8beb)

**Comment by cpp-red-lion** [comment]
These issues were fixed in version 2.0 (just released).

**Pull request closed without merging**
