### PR TITLE
fixes related to the VSIX

### LINKED ISSUE #346: putting empty lines in the compiler flags list generates an error
Just put an empty line in the compile flags and compile any file.

```
Start Clang Compile

C:\Users\dogilvie\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\3ulf35s3.fwe\clang-build.ps1 : Cannot bind 
argument to parameter 'aClangCompileFlags' because it is an empty string.
At line:1 char:305
+ ... clang-flags ('-Wall','','-fms-compatibility-version=19.10','-Wmicroso ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [clang-build.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,clang-build.ps1
 

Done Clang Compile
```

I have a fix and will add it to #342

### PR DESCRIPTION
**Pull request by mrexodia**
closes #346

### CODE REVIEW

**Comment by Enache-Ionut** [comment]
Hi,

We found a better way to add all the `.ps1` files and ignore all `.tests.ps1` files, you can see it [here](https://github.com/Caphyon/clang-power-tools/pull/347).
We also want to keep the `clang-format.exe` in GitHub because the project will not work anymore without it if someone make a clone or download the repository.

If you will remove your first two commits related to what I said above we will gladly accept your pull request.

Thank you for the help!

**Comment by mrexodia** [comment]
@Enache-Ionut whatever works better for you 👍

As for `clang-format.exe` it's currently not on the repository (I had to manually copy it in) so I don't really understand the problem with that...

**Comment by mrexodia** [comment]
I removed the commit for the `psClang` folder and rebased on `master`.

**Comment by Enache-Ionut** [comment]
We have the `clang-format.exe` in the repository, it can be found [here](https://github.com/Caphyon/clang-power-tools/tree/master/ClangPowerTools/ClangPowerTools/llvm/bin). We also include `clang-format.exe` in the VSIX package and in this way the extension can be used immediately after installation. This is the reason why we can't add `clang-format.exe` in `.gitignore` file.

**Comment by mrexodia** [comment]
Ah okay, so then it just means clang-format is not properly included in the csproj, let me fix that instead...

**Comment by mrexodia** [comment]
Alright, this should fix the compilation error I encountered before. The destination path in the VSIX is `.` so everything looks correct. One suggestion I have is to include an AppVeyor config so that people can get builds from `master`.

**Comment by cpp-red-lion** [comment]
Hi,

We don't have experience with AppVeyor.
If you can help us by contributing a separate PR with AppVeyor config, that would be awesome.

Thanks.

**Comment by mrexodia** [comment]
Will do!

**Pull request merged**
