### PR TITLE
AppVeyor

### PR DESCRIPTION
**Pull request by mrexodia**
Okay, this is the AppVeyor branch. It is only a preview because #342 fixes the solution build error. It is also using my personal account in the README.

Could you create a [new project](https://ci.appveyor.com/projects/new) for Caphyon/clang-power-tools? If you could give me a link to your AppVeyor project's badge I can link to that one instead of my personal account.

### CODE REVIEW

**Comment by mrexodia** [comment]
I rebased the branch on master.

**Comment by mrexodia** [comment]
Any updates on this? I see you also have some tests for the powershell scripts, we could run those in AppVeyor too...

**Comment by cpp-red-lion** [comment]
Not yet, sorry.

**Comment by mrexodia** [comment]
Hello, any updates on this?

**Comment by hprica** [comment]
Thank you very much for your suggestion @mrexodia.

Unfortunately, at this time we don't have a robust unit testing infrastructure for Clang Power Tools, but we are looking into improving this in the near feature. 

Because we have not decided on what Continuous Integration and Deployment service we'll use and how we'll handle permissions to our private and company repositories that are also using this GitHub, we are closing the merge request.

**Pull request closed without merging**
